// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService is a Wails service for file log streaming.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CloseFile stops the log stream for the given tabId.
 */
export function CloseFile(tabId: string): $CancellablePromise<void> {
    return $Call.ByID(3073934691, tabId);
}

/**
 * OpenFile opens a file for streaming in the given tab.
 * Called from the frontend when the user opens a file.
 */
export function OpenFile(tabId: string, path: string): $CancellablePromise<void> {
    return $Call.ByID(2760567869, tabId, path);
}
