// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as session$0 from "../../../../litvivangett/weblogview/internal/session/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "log-error": session$0.LogErrorEvent;
            "log-initial": session$0.LogLinesEvent;
            "log-initial-chunk": session$0.LogLinesEvent;
            "log-initial-complete": session$0.LogLoadEvent;
            "log-initial-start": session$0.LogLoadEvent;
            "log-lines": session$0.LogLinesEvent;
        }
    }
}
