//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "../../../../litvivangett/weblogview/internal/session/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "log-error": $$createType0,
        "log-initial": $$createType1,
        "log-lines": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = session$0.LogErrorEvent.createFrom;
const $$createType1 = session$0.LogLinesEvent.createFrom;

configure();
