// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * K8sContext represents a Kubernetes context
 */
export class K8sContext {
    "name": string;
    "cluster": string;
    "namespace": string;
    "isCurrent": boolean;

    /** Creates a new K8sContext instance. */
    constructor($$source: Partial<K8sContext> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("cluster" in $$source)) {
            this["cluster"] = "";
        }
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("isCurrent" in $$source)) {
            this["isCurrent"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new K8sContext instance from a string or object.
     */
    static createFrom($$source: any = {}): K8sContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new K8sContext($$parsedSource as Partial<K8sContext>);
    }
}

/**
 * K8sOpenConfig contains parameters for opening a K8s log stream.
 */
export class K8sOpenConfig {
    "namespace": string;
    "podName": string;
    "containerName": string;

    /** Creates a new K8sOpenConfig instance. */
    constructor($$source: Partial<K8sOpenConfig> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("podName" in $$source)) {
            this["podName"] = "";
        }
        if (!("containerName" in $$source)) {
            this["containerName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new K8sOpenConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): K8sOpenConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new K8sOpenConfig($$parsedSource as Partial<K8sOpenConfig>);
    }
}
