// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LogErrorEvent is emitted when an error occurs for a tab.
 */
export class LogErrorEvent {
    "tabId": string;
    "error": string;

    /** Creates a new LogErrorEvent instance. */
    constructor($$source: Partial<LogErrorEvent> = {}) {
        if (!("tabId" in $$source)) {
            this["tabId"] = "";
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogErrorEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): LogErrorEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogErrorEvent($$parsedSource as Partial<LogErrorEvent>);
    }
}

/**
 * LogLinesEvent is emitted when new log lines arrive for a tab.
 */
export class LogLinesEvent {
    "tabId": string;
    "lines": string[];

    /** Creates a new LogLinesEvent instance. */
    constructor($$source: Partial<LogLinesEvent> = {}) {
        if (!("tabId" in $$source)) {
            this["tabId"] = "";
        }
        if (!("lines" in $$source)) {
            this["lines"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLinesEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): LogLinesEvent {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("lines" in $$parsedSource) {
            $$parsedSource["lines"] = $$createField1_0($$parsedSource["lines"]);
        }
        return new LogLinesEvent($$parsedSource as Partial<LogLinesEvent>);
    }
}

/**
 * LogLoadEvent is emitted for log load lifecycle markers.
 */
export class LogLoadEvent {
    "tabId": string;

    /** Creates a new LogLoadEvent instance. */
    constructor($$source: Partial<LogLoadEvent> = {}) {
        if (!("tabId" in $$source)) {
            this["tabId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogLoadEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): LogLoadEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogLoadEvent($$parsedSource as Partial<LogLoadEvent>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
