// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService is the Wails-registered service that exposes session
 * management to the frontend. It wraps SessionManager and only exposes
 * methods with concrete-type parameters, avoiding binding generator warnings
 * from interface-typed parameters (Watcher, error).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CloseTab stops the log stream for a tab. Called from the frontend.
 */
export function CloseTab(tabId: string): $CancellablePromise<void> {
    return $Call.ByID(1383705502, tabId);
}
