// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * K8sService is a Wails service for Kubernetes operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as watcher$0 from "../../watcher/models.js";

/**
 * ListContainers returns container names in the given pod.
 */
export function ListContainers($namespace: string, pod: string): $CancellablePromise<string[]> {
    return $Call.ByID(219264867, $namespace, pod).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListContexts returns available Kubernetes contexts.
 */
export function ListContexts(): $CancellablePromise<watcher$0.K8sContext[]> {
    return $Call.ByID(638873463).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ListNamespaces returns all namespaces in the current context.
 */
export function ListNamespaces(): $CancellablePromise<string[]> {
    return $Call.ByID(1021719387).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListPods returns pod names in the given namespace.
 */
export function ListPods($namespace: string): $CancellablePromise<string[]> {
    return $Call.ByID(1845603335, $namespace).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * OpenK8s opens a K8s pod log stream in the given tab.
 */
export function OpenK8s(tabId: string, config: watcher$0.K8sOpenConfig): $CancellablePromise<void> {
    return $Call.ByID(2768275769, tabId, config);
}

/**
 * SwitchContext changes the active Kubernetes context.
 */
export function SwitchContext(contextName: string): $CancellablePromise<void> {
    return $Call.ByID(3822933750, contextName);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = watcher$0.K8sContext.createFrom;
const $$createType2 = $Create.Array($$createType1);
