// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SettingsResponse is the data returned by GetSettings.
 */
export class SettingsResponse {
    "tailLines": number;
    "renderAnsiTopPane": boolean;
    "renderAnsiBottomPane": boolean;
    "pollingIntervalMs": number;
    "sourceNameFormat": string;

    /** Creates a new SettingsResponse instance. */
    constructor($$source: Partial<SettingsResponse> = {}) {
        if (!("tailLines" in $$source)) {
            this["tailLines"] = 0;
        }
        if (!("renderAnsiTopPane" in $$source)) {
            this["renderAnsiTopPane"] = false;
        }
        if (!("renderAnsiBottomPane" in $$source)) {
            this["renderAnsiBottomPane"] = false;
        }
        if (!("pollingIntervalMs" in $$source)) {
            this["pollingIntervalMs"] = 0;
        }
        if (!("sourceNameFormat" in $$source)) {
            this["sourceNameFormat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsResponse($$parsedSource as Partial<SettingsResponse>);
    }
}

/**
 * SettingsUpdate is the data accepted by UpdateSettings.
 */
export class SettingsUpdate {
    "tailLines": number;
    "renderAnsiTopPane": boolean | null;
    "renderAnsiBottomPane": boolean | null;
    "pollingIntervalMs": number;
    "sourceNameFormat": string;

    /** Creates a new SettingsUpdate instance. */
    constructor($$source: Partial<SettingsUpdate> = {}) {
        if (!("tailLines" in $$source)) {
            this["tailLines"] = 0;
        }
        if (!("renderAnsiTopPane" in $$source)) {
            this["renderAnsiTopPane"] = null;
        }
        if (!("renderAnsiBottomPane" in $$source)) {
            this["renderAnsiBottomPane"] = null;
        }
        if (!("pollingIntervalMs" in $$source)) {
            this["pollingIntervalMs"] = 0;
        }
        if (!("sourceNameFormat" in $$source)) {
            this["sourceNameFormat"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsUpdate instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsUpdate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsUpdate($$parsedSource as Partial<SettingsUpdate>);
    }
}
