// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is a Wails service for application settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings returns the current application settings.
 */
export function GetSettings(): $CancellablePromise<$models.SettingsResponse> {
    return $Call.ByID(3621314374).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * UpdateSettings updates the application settings.
 */
export function UpdateSettings(update: $models.SettingsUpdate): $CancellablePromise<void> {
    return $Call.ByID(4124316037, update);
}

// Private type creation functions
const $$createType0 = $models.SettingsResponse.createFrom;
