// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RecentService handles recent files and namespaces
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * AddRecentFile adds a file path to the recent files list
 */
export function AddRecentFile(path: string): $CancellablePromise<void> {
    return $Call.ByID(1884833581, path);
}

/**
 * AddRecentNamespace adds a namespace to the recent namespaces list
 */
export function AddRecentNamespace($namespace: string): $CancellablePromise<void> {
    return $Call.ByID(4144475134, $namespace);
}

/**
 * GetRecentFiles returns the list of recently opened files
 */
export function GetRecentFiles(): $CancellablePromise<string[]> {
    return $Call.ByID(1233089455).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetRecentNamespaces returns the list of recently used Kubernetes namespaces
 */
export function GetRecentNamespaces(): $CancellablePromise<string[]> {
    return $Call.ByID(1437839780).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
